server:
  port: 8080
  servlet:
    context-path: /api

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: test.anhnguyenthe29112004@gmail.com
    password: gxwdxlnfjdqkzpbt
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  datasource:
    url: jdbc:postgresql://localhost:5432/loan_db
    username: theanh
    password: 100804
  jpa:
    show-sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
jwt:
  signerKey: 2309abbd-d085-4386-8dee-b0e008713c62
  access-token-expiration: 3600
  refresh-duration: 36000